apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
		[...]
parameters:
	- description: Password used for Redis authentication
	  from: '[A-Z0-9]{8}'
	  generate: expression
	  name: REDIS_PASSWORD
labels:
  redis: master
