apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,nosql"
		[...]
parameters:
	- description: Password used for Redis authentication
	  from: '[A-Z0-9]{8}'
	  generate: expression
	  name: REDIS_PASSWORD
labels:
  redis: master
